title: Maisha Zahrani
email: zahranimaisha@gmail.com
description: Saya berasal dari Lhokseumawe, sekarang belajar di Politeknik Negeri Lhokseumawe sebagai mahasiswa jurusan Teknologi Informasi dan Komputer

url: 'https://maishazahrani.github.io'

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag